"""Assemblage du contenu : modules, glossaire, simulateur d'entretien, plan de travail."""
from content_a import MODULES_A
from content_b import MODULES_B
from content_c import MODULES_C

MODULES = MODULES_A + MODULES_B + MODULES_C

PLAN = [
    ("Semaine 1", "Modules 1 et 2", "Diagnostic stratégique, marché & concurrence", "4 h"),
    ("Semaine 2", "Module 3", "États financiers + laboratoire Ratios & cash", "3 h"),
    ("Semaine 3", "Module 4", "Création de valeur + laboratoire VAN / TRI", "3 h"),
    ("Semaine 4", "Module 5", "Valorisation + laboratoires Valorisation et DCF", "4 h"),
    ("Semaine 5", "Module 6", "Business plan & scénarios + laboratoire BP", "3 h"),
    ("Semaine 6", "Module 7", "M&A & synergies + laboratoire Synergies", "4 h"),
    ("Semaine 7", "Modules 8 et 9", "Investment memo, corporate strategy, matrice de décision", "4 h"),
    ("Semaine 8", "Module 10 + entretien", "Cas final COMEX + 10 questions d'entretien", "5 h"),
]

GLOSSARY = {
    "BFR": "Besoin en fonds de roulement : stocks + créances clients − dettes fournisseurs. Cash immobilisé dans le cycle d'exploitation.",
    "CAGR": "Taux de croissance annuel composé : (valeur finale / valeur initiale)^(1/n) − 1.",
    "CAPEX": "Dépenses d'investissement (immobilisations). On distingue maintenance et croissance.",
    "Carve-out": "Séparation d'une activité d'un groupe vendeur pour la céder ou la rendre autonome ; implique séparation des systèmes, des contrats et des fonctions support.",
    "Closing": "Date de réalisation effective de la transaction et de transfert du contrôle (J0).",
    "Conversion cash": "FCF / EBITDA : part de l'EBITDA transformée en cash libre.",
    "DCF": "Discounted Cash-Flow : valorisation par actualisation des flux de trésorerie futurs.",
    "Deadlock": "Situation de blocage entre partenaires d'une JV ; traitée par des mécanismes d'escalade, de médiation ou de sortie.",
    "Due diligence": "Revue approfondie d'une cible avant l'engagement (financière, juridique, fiscale, commerciale, opérationnelle, IT, RSE).",
    "DSO / DIO / DPO": "Délais en jours : créances clients, stocks, dettes fournisseurs.",
    "Earn-out": "Complément de prix conditionné à la performance future de la cible.",
    "EBITDA": "Résultat d'exploitation avant amortissements et dépréciations ; indicateur de performance opérationnelle (≠ cash).",
    "EBIT": "Résultat d'exploitation après amortissements.",
    "Enterprise Value (EV)": "Valeur des opérations d'une entreprise, indépendante de son financement.",
    "Equity Value": "Valeur revenant aux actionnaires = EV − dette nette ± ajustements.",
    "EVA": "Valeur économique ajoutée = NOPAT − WACC × capitaux employés.",
    "Fact base": "Socle factuel d'un diagnostic stratégique : activité, marché, risques, opportunités, enjeux.",
    "FCF": "Free cash-flow : EBITDA − impôts cash − variation de BFR − CAPEX.",
    "Goodwill": "Écart d'acquisition : prix payé − juste valeur des actifs nets identifiables.",
    "Joint-venture (JV)": "Entité contrôlée conjointement par deux partenaires ou plus, pour un projet commun.",
    "Levier": "Dette nette / EBITDA ; mesure la capacité de remboursement.",
    "MECE": "Mutuellement exclusif, collectivement exhaustif : critère de qualité d'une structuration en options.",
    "NDA": "Accord de confidentialité signé avant l'échange d'informations sensibles.",
    "NOPAT": "Résultat d'exploitation après impôt théorique, avant frais financiers.",
    "PMI": "Post-merger integration : intégration après acquisition.",
    "ROCE": "NOPAT / capitaux employés ; rentabilité du capital engagé.",
    "ROIC": "Return on invested capital : proche du ROCE, selon la définition du capital investi.",
    "SAM / SOM / TAM": "Marché total, marché adressable par l'offre, part réalistement capturable.",
    "SPA": "Share Purchase Agreement : contrat d'acquisition de titres.",
    "Synergies": "Gains attendus de la combinaison : coûts, revenus, financières.",
    "TRI (IRR)": "Taux de rendement interne : taux qui annule la VAN.",
    "TSA": "Transitional Service Agreement : services fournis par le vendeur à l'acquéreur pendant une période transitoire.",
    "Valeur terminale": "Valeur de l'entreprise au-delà de l'horizon explicite de prévision (Gordon-Shapiro ou multiple).",
    "VAN (NPV)": "Valeur actuelle nette : somme des flux actualisés − investissement initial.",
    "WACC": "Coût moyen pondéré du capital ; taux d'actualisation et seuil de création de valeur.",
}

INTERVIEW = [
    {"q": "Pourquoi recommanderiez-vous une JV plutôt qu'une acquisition pour entrer dans un nouveau pays ?",
     "expected": [["vitesse", "rapide", "délai"], ["capital", "investissement", "cash"], ["risque", "intégration"], ["partenaire", "capacité", "réseau", "licence"], ["gouvernance", "contrôle", "deadlock"]],
     "model": "Je recommande une JV si le partenaire apporte un accès marché ou des licences que nous ne pouvons pas répliquer rapidement. Premièrement, la vitesse : accès au marché en 12 à 18 mois contre plus de 3 ans en organique. Deuxièmement, le capital : l'investissement est partagé, ce qui limite l'exposition. Troisièmement, le risque d'intégration est moindre qu'en acquisition. Le point de vigilance est la gouvernance : matières réservées, deadlock, sortie. En synthèse, je recommande la JV sous conditions, avec une option d'achat future."},
    {"q": "Comment définiriez-vous le prix maximum que nous sommes prêts à payer pour une cible ?",
     "expected": [["valeur autonome", "stand-alone", "standalone", "dcf", "multiple"], ["synergie"], ["risque", "exécution"], ["coût", "intégration", "one-off", "séparation"], ["quote-part", "partage", "part des synergies", "plafond"]],
     "model": "Je pars de la valeur autonome de la cible (DCF et multiples), puis j'ajoute les synergies nettes du risque d'exécution et des coûts one-off d'intégration. Je ne cède qu'une quote-part de ces synergies au vendeur, par exemple 30 à 50 %, afin de conserver une marge pour le risque. Le prix plafond est donc valeur autonome + quote-part de synergies nettes. J'en déduis une première offre plus basse pour garder une marge de négociation."},
    {"q": "Un scénario stratégique crée de la valeur mais dépasse la capacité d'exécution de la BU. Que faites-vous ?",
     "expected": [["capacité", "ressource"], ["phas", "étap", "jalon"], ["priorit"], ["partenaire", "externe", "renfort", "accompagn"], ["gouvernance", "kpi", "suivi"]],
     "model": "Je ne renonce pas au scénario, mais je le phase. Je priorise les actions à plus forte valeur et plus faible risque, je définis des jalons de décision et je renforce la capacité d'exécution (ressources internes, partenaire externe). Je mets en place une gouvernance de suivi avec des KPIs pour déclencher des décisions correctives. En conclusion, la valeur ne vaut que si elle est exécutable."},
    {"q": "Comment challengez-vous un business plan présenté par une BU ?",
     "expected": [["historique", "réalis"], ["driver", "hypoth"], ["benchmark", "pair", "comparab"], ["cash", "bfr", "capex"], ["sensibilit", "scénario", "downside"]],
     "model": "Je commence par comparer l'historique et les prévisions : toute rupture de trajectoire doit être expliquée. Je vérifie les drivers de revenus et de coûts, leur réalisme commercial et industriel, puis le cash (capex, BFR). Je benchmarke les marges contre des pairs et je teste des sensibilités et un scénario downside sur les hypothèses les plus agressives. Je conclus par les 3 hypothèses sur lesquelles repose la décision."},
    {"q": "Que doit contenir une note COMEX sur un projet d'acquisition ?",
     "expected": [["décision", "recommand"], ["thèse", "rationale", "pourquoi"], ["valorisation", "prix", "economics", "van", "roce"], ["risque"], ["condition", "prochaines étapes", "plan"]],
     "model": "La décision demandée en première phrase, puis la thèse en trois piliers chiffrés, la valorisation et les economics (prix, VAN, ROCE vs WACC) avec des scénarios, les principaux risques et leurs mitigations, et enfin les conditions suspensives et les prochaines étapes. L'objectif est que le comité puisse décider en dix minutes."},
    {"q": "Expliquez la différence entre EBITDA et free cash-flow à un dirigeant non financier.",
     "expected": [["cash", "trésorerie"], ["bfr", "fonds de roulement"], ["capex", "investissement"], ["impôt"], ["conversion", "ebitda"]],
     "model": "L'EBITDA mesure la performance opérationnelle avant amortissements, mais ce n'est pas du cash disponible. Pour obtenir le free cash-flow, on retire les impôts, la variation du BFR et les capex. Une entreprise peut avoir un EBITDA élevé et très peu de cash si elle investit beaucoup ou si son BFR dérive. C'est pourquoi je regarde la conversion cash FCF / EBITDA."},
    {"q": "Comment valoriseriez-vous une cible dans un secteur où il existe peu de comparables ?",
     "expected": [["dcf", "flux"], ["multiple", "comparab"], ["transaction"], ["sensibilit", "fourchette"], ["wacc", "risque"]],
     "model": "J'élargis d'abord le périmètre de comparables (secteurs adjacents, géographies proches) en justifiant chaque choix. Je m'appuie davantage sur le DCF, avec un WACC reflétant le risque spécifique, et je croise avec les transactions précédentes. Je présente une fourchette et des sensibilités plutôt qu'un chiffre unique, en explicitant les hypothèses qui font bouger la valeur."},
    {"q": "Quels sont, selon vous, les principaux risques d'un carve-out et comment les chiffrez-vous ?",
     "expected": [["tsa", "transition"], ["si", "système", "it"], ["coût", "séparation", "dis-synergie"], ["calendrier", "délai", "durée"], ["plan", "j0", "100 jours", "intégration"]],
     "model": "Les principaux risques sont la dépendance aux services du vendeur, la séparation du système d'information, les coûts de séparation et les dis-synergies, et le calendrier de sortie des TSA. Je les chiffre en définissant le modèle opérationnel cible dès la due diligence, puis en estimant coûts one-off et durée des TSA, et en les intégrant au business case et au prix. Un plan J0 / 100 jours cadre ensuite l'exécution."},
    {"q": "Comment arbitrez-vous entre deux projets d'investissement mutuellement exclusifs ?",
     "expected": [["van", "valeur actuelle"], ["wacc", "coût du capital"], ["taille", "capital", "profitabilité"], ["risque"], ["stratég", "aligne", "raison d'être"]],
     "model": "Je compare d'abord la VAN au même WACC, ajusté du risque de chaque projet. J'examine l'indice de profitabilité si le capital est rationné et je teste la robustesse par scénarios. Puis je considère les risques non financiers et l'alignement stratégique. Je recommande le projet qui crée le plus de valeur de façon robuste, et non celui au TRI le plus élevé."},
    {"q": "Pourquoi souhaitez-vous évoluer d'un rôle spécialisé (IT, M&A, opérations) vers un rôle de stratégie groupe ?",
     "expected": [["valeur", "création de valeur"], ["m&a", "acquisition", "transaction"], ["transvers", "business", "vision"], ["apport", "atout", "expérience"], ["apprendre", "compétence", "finance", "stratég"]],
     "model": "Mon expérience du M&A, de la due diligence, du carve-out et de l'intégration m'a donné une vision transverse des enjeux business, finance et opérations. Je souhaite désormais agir plus en amont, sur la création de valeur et la définition du portefeuille. Mon atout est de connaître la réalité de l'exécution ; j'ai renforcé mes compétences en finance et en analyse stratégique pour assumer ce rôle. Je peux ainsi fiabiliser les business cases et accélérer l'intégration."},
]
